### ISSUE TITLE
Blue screens can't be displayed even if the exception is not handled causing an instant reboot.

### ISSUE THREAD

**Issue by can1357** [can1357/ByePg#1]

**Comment by nicholaskunes** [comment]
I assume this is the reason the Exception Demo fails immediately on Win10. Any update on when we should expect to see this resolved, or if at all.

**Comment by can1357** [comment]
Which version of Windows 10? I tried it on 1607 and it seems to work for me.

**Comment by nicholaskunes** [comment]
Version	10.0.18362 Build 18362
Reboots the system instantaneously no crash-dump. No VM. Stock version of verified Windows on a AMD laptop. FreeSEH.sys runs as expected.

**Comment by nicholaskunes** [comment]
The exception it failed to handle is Bug Check 0x7F: UNEXPECTED_KERNEL_MODE_TRAP
