### ISSUE TITLE
HalCallbacks::Register() Issue

### ISSUE THREAD

**Issue by Shhoya** [can1357/ByePg#14]
Hi, i'm newbie....
The "ExHook" test was run on a virtual machine. (Win10 (1809)) The build went well and I loaded the driver via "OSR Loader" but freezing occurred. I checked that HalCallbacks :: Register () freezes while hooking "HalNotifyProcessorFreeze"... 
The issue is that freezing takes place as soon as you replace "HalPrivateDispatchTable" + 0x1A8 ("HalpTimerNotifyProcessorFreeze") with a hooking function ("HkHalTimerNotifyProcessorFreeze"). 
Do you know how to solve the problem?

Freeze point:
![이미지 1](https://user-images.githubusercontent.com/36813165/73820207-9dbb0480-4834-11ea-9ea7-e6a61bea81d6.png)

**Comment by can1357** [comment]
Are you using Windows kernel debugger?

**Comment by Shhoya** [comment]
> Are you using Windows kernel debugger?

Yes, To study, I loaded and debug the driver using VirtualKD. Is this a problem?

**Comment by can1357** [comment]
Yes, KD uses the same freezing mechanism so it will not work. Switch to a hypervisor based debugger like VMWare's GDB stub.
