### ISSUE TITLE
Can I use ByePG in this case?

### ISSUE THREAD

**Issue by ReverseKR** [can1357/ByePg#17]
I want to hide process by modyifying ActiveProcessLinks, but it causes bsod by PatchGuard. Even I use ByePG, result is same.
Can I use ByePG in this case?

Bsod code is CRITICAL_STRUCTURE_CORRUPTION

This bsod doesn't contain context in bugcheck args.

**Comment by hzqst** [comment]
no you can not.

**Comment by zer0call** [comment]
> no you can not.

Why not?

**Comment by hzqst** [comment]
> > no you can not.
> 
> Why not?

PatchGuard clears stack memory before calling KeBugCheck so you won't be able to unwind the stack.
