### ISSUE TITLE
Windows 7 cant find ntoskrnl.exe and KiFreezeExecutionLock

### ISSUE THREAD

**Issue by InvisK** [can1357/ByePg#4]
Hello, i just test in windows 7 and look like ByePGLib is cant find ntoskrnl.exe and KiFreezeExecutionLock, can you help me fix it ?
![Capture](https://user-images.githubusercontent.com/17687394/67174162-4ad75180-f3eb-11e9-9fbd-2f0d55636be1.JPG)

**Comment by can1357** [comment]
HalNotifyProcessorFreeze is only implemented after Windows 8 so ByePgLib won't work for Windows 7, sorry 😢
