### ISSUE TITLE
Auto restart after ~1 hour

### ISSUE THREAD

**Issue by InvisK** [can1357/ByePg#5]
hello im using ExceptionHookingDemo to disarm PG but i got Auto restart with no BSOD after about 1 hour, what can be the reason ?

**Comment by can1357** [comment]
Auto restart is most likely a BSOD due to Issue #1 , if you are using a VM I would try placing a breakpoint at https://github.com/can1357/ByePg/blob/master/ByePgLib/ExceptionHandler.h#L99

**Comment by InvisK** [comment]
oh sorry i have wrong understand about ContextRecord so it's because of me, thanks.
