### ISSUE TITLE
is it right to bypass mem corrupt ?

### ISSUE THREAD

**Issue by InvisK** [can1357/ByePg#8]
hello, i want to hook something but i got auto restart, is this snippet good to bypass mem corrupt guard ? thanks
```
ByePgInitialize( [ ] ( CONTEXT* ContextRecord, EXCEPTION_RECORD* ExceptionRecord ) -> LONG
	{
		if ( ExceptionRecord->ExceptionCode == ( CRITICAL_STRUCTURE_CORRUPTION << 32 | KERNEL_SECURITY_CHECK_FAILURE ) )
		{
			ContextRecord->Rip++;
			return EXCEPTION_CONTINUE_EXECUTION;
		}
		return EXCEPTION_EXECUTE_HANDLER;
	}, Verbose );
```

**Comment by can1357** [comment]
That won't work. Putting the fact that logic is invalid, this project is not disarming patchguard. It simply avoids it. You need to think of a way to hook whatever it is that you want using exceptions.

**Comment by InvisK** [comment]
> That won't work. Putting away the fact that your code is wrong, this project is not disarming patchguard. It simply avoids it. You need to think of a way to hook whatever it is that you want using exceptions.

oh thank you for the answer, do you know any Exception can cause when patchguard being fire ? i dont want to disarming patchguard, i just want to catch before it being fire
